"""
agents/task_agent.py — Core task-processing agent.

Responsibility:
  Accepts a user task, decomposes it into labelled sub-steps, and produces
  a synthesised answer by running each sub-step through the LLM simulator.

Why a dedicated TaskAgent?
  Many orchestration workflows start with a "do the thing" stage that is
  too broad for a narrow specialist (Summariser, Classifier).  TaskAgent
  is that general-purpose workhorse.  It is intentionally kept simple —
  complexity belongs in the orchestrator's routing logic, not here.

Output contract:
  Returns a single AgentResult whose `output` field is the fully reasoned
  answer, and whose `metadata` contains the sub-step breakdown for tracing.
"""

from typing import Optional

from agents.base_agent import AgentResult, BaseAgent
from utils.llm_simulator import llm
from utils.logger import get_logger

logger = get_logger(__name__)

# Sub-steps that the TaskAgent always performs, in order.
# In a real system these would be dynamically generated by an LLM planner.
_PIPELINE_STEPS = [
    ("understand",  "Understand the core intent and constraints of the task."),
    ("decompose",   "Break the task into ordered, atomic sub-problems."),
    ("execute",     "Resolve each sub-problem using available knowledge."),
    ("synthesise",  "Merge sub-problem answers into a coherent final response."),
    ("validate",    "Verify the response satisfies the original task requirements."),
]


class TaskAgent(BaseAgent):
    """
    General-purpose task execution agent.

    Runs a fixed five-stage pipeline (understand → decompose → execute →
    synthesise → validate) against the LLM simulator, then returns the
    synthesised answer as the primary output.
    """

    def __init__(self) -> None:
        super().__init__(
            name="TaskAgent",
            description=(
                "General-purpose agent that decomposes a task into sub-steps "
                "and synthesises a final answer."
            ),
        )

    def _run(self, input_text: str, context: Optional[str]) -> AgentResult:
        logger.debug("TaskAgent pipeline starting | input_len=%d", len(input_text))

        step_outputs: list[dict] = []
        total_tokens = 0
        final_output = ""

        for step_key, step_instruction in _PIPELINE_STEPS:
            prompt = f"{step_instruction}\n\nTask: {input_text}"
            response = llm.complete(prompt, context=context if step_key == "execute" else None)

            step_outputs.append({
                "step": step_key,
                "instruction": step_instruction,
                "output": response.content,
                "confidence": response.confidence,
                "tokens": response.tokens_used,
            })
            total_tokens += response.tokens_used

            # The synthesise step produces the canonical answer
            if step_key == "synthesise":
                final_output = response.content

            logger.debug(
                "TaskAgent step=%s confidence=%.2f tokens=%d",
                step_key, response.confidence, response.tokens_used,
            )

        # Overall confidence = mean of step confidences
        avg_confidence = sum(s["confidence"] for s in step_outputs) / len(step_outputs)

        return AgentResult(
            agent_name=self.name,
            success=True,
            output=final_output,
            confidence=round(avg_confidence, 3),
            tokens_used=total_tokens,
            metadata={"pipeline_steps": step_outputs},
        )
